theme = "soda"

[editor]
color-modes = true
bufferline = "always"
default-yank-register = "+"
line-number = "relative"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "diagnostics"]
right = ["version-control", "position", "file-encoding"]

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "warning"

[editor.lsp]
display-progress-messages = true

[editor.indent-guides]
render = true
skip-levels = 1
